node_js:
  - 12 # Level of Node.js to use
cache:
  directories:
  - node_modules # Cache the node_modules folder for quicker build times
script:
  - next build # Runs next build
  - next export # Runs next export and generates the out directory
  - touch out/.nojekyll # Creates a file telling Github not to build the project using Jekyll
deploy:
  provider: pages # Informs Travis this is a deployment to GitHub Pages
  skip_cleanup: true # Prevents Travis from resetting the working directory made during the build
  github_token: a43d8534ae6aa3904a77b05c14c0dcb2cdd2e45a
  local_dir: out # Directory to push to the gh-pages branch
  on:
    branch: master # Only deploy when the build is on master branch